name: 🧪 Lint and test

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [16, 18, 20]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8

      - run: pnpm recursive install
      - name: Linting
        continue-on-error: true
        run: pnpm lint

      - name: Run the tests
        run: pnpm coverage

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: 🧪 Unit tests
          path: .coverage/junit.xml
          reporter: jest-junit

      - name: Build all
        run: pnpm build-all
